name: 'Check for O and M documents'
description: 'Check for O and M documents'
inputs:
  operation_path:
    description: 'Path to the operation documents'
    required: true
    default: 'docs/operations/'
runs:
  using: 'composite'
  steps:
    - name: 'Checkout codebase' 
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: 'Check for O and M documents'
      run: |
        SCRIPT_HOME="/home/runner/work/_actions/nn-dma/check_o_and_m_files/main/scripts/" 
        echo "Checking for O and M documents"
        cd ${{ github.workspace }}
        SCRIPT_PATH="${SCRIPT_HOME}o_and_m.sh"
        chmod +x $SCRIPT_PATH
        o_and_m_files=$(${SCRIPT_PATH} ${{ inputs.operation_path }})
        echo "O and M files: $o_and_m_files"
        echo $SCRIPT_PATH
      shell: bash
 

