name: "Check for O and M documents"
description: "Check for O and M documents"
inputs:
  operation_path:
    description: "Path to the operation documents"
    required: true
    default: "docs/operations/"

outputs:
  o_and_m_files:
    description: "O and M files"
    value: ${{ steps.o_and_m_files.outputs.o_and_m_files }}

runs:
  using: "composite"
  steps:
    - name: "Checkout codebase"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: "Check for O and M documents"
      id: o_and_m_files
      run: |
        SCRIPT_HOME="/home/runner/work/_actions/NovoNordisk-OpenSource/check_o_and_m_files/v1.0.0/scripts/" 
        echo "Checking for O and M documents"
        SCRIPT_PATH="${SCRIPT_HOME}o_and_m.sh"
        chmod +x $SCRIPT_PATH
        o_and_m_files=$(${SCRIPT_PATH} ${{ inputs.operation_path }})
        o_and_m_files_updated=$(${SCRIPT_PATH} ${{ inputs.operation_path }} | tail -n 1) # get only true/false
        echo "O and M files: $o_and_m_files"
        if [ "$o_and_m_files_updated" == false ]; then
          echo "o_and_m_files=false" >> "$GITHUB_OUTPUT"
          echo "Approval workflow will NOT be triggered"
        else
          echo "o_and_m_files=true" >> "$GITHUB_OUTPUT"
          echo "Approval workflow WILL BE triggered"
        fi
      shell: bash
