name: 'Check for O and M documents'
description: 'Check for O and M documents'
inputs:
  operation_path:
    description: 'Path to the operation documents'
    required: true
    default: 'docs/operations/'
  maintenance_path:
    description: 'Path to the maintenance documents'
    required: true
    default: 'docs/maintenance/'
# Removing the template_repo input for now and keep actions convoluted
#  template_repo:
#    description: 'path to template repository'
#    required: true
#    default: '/nn-dma/reference/template/'

runs:
  using: 'composite'
  steps:
    - Name: 'Checkout codebase' 
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
# Removing the template_repo input for now and keep actions convoluted
#    - Name: 'Checkout template repository'
#      uses: actions/checkout@v2
#      with:
#        repository: ${{ inputs.template_repo }}
#        path: '/nn-dma/reference/template/
    - Name: 'Check for O and M documents'
      run: |
        echo "Checking for O and M documents"
        cd ${{ github.workspace }}
        SCRIPT_PATH="/home/runner/work/_actions/nn-dma/check_o_and_m_files/scripts/check_om.sh"
        chmod +x $SCRIPT_PATH
        o_and_m_files=$(${SCRIPT_PATH} ${{ inputs.operation_path }}
        echo "O and M files: $o_and_m_files"
        echo $SCRIPT_PATH
      shell: bash
    
    - 

